subprojects {
    group = 'dev.folderion'
    version = '0.1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    plugins.withId('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }

    plugins.withId('java-library') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }
}
