plugins {
    id 'java'
    id 'application'
}

dependencies {
    implementation project(':folderion')

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'dev.folderion.crawler.CentrisCrawlerApp'
}

tasks.named('run', JavaExec) {
    workingDir = rootProject.projectDir
}
